#!/usr/bin/env python3
import shutil
import subprocess
import sys

# Get the commit file
with open(sys.argv[1]) as fp:  # The first argument is the file
    message = fp.read()

first_line = message.splitlines()[0]

# amends or `-m` message have a non-empty first line of a commit message
if not first_line:
    git = shutil.which("git")
    find_branch_cmd = [git, "rev-parse", "--abbrev-ref", "HEAD"]
    branch = subprocess.check_output(find_branch_cmd).decode().strip()

    with open(sys.argv[1], "w") as fp:
        fp.write("[{}] {}".format(branch, message))
